[package]
name = "novelenv"
version = "0.1.0"
edition = "2021"
description = "Novel writing environment management tool"

[[bin]]
name = "novel"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }